### ISSUE TITLE
`withEventHandler` is not exported by the library

### ISSUE THREAD

**Issue by Toeler** [gabrielguerrero/ngrx-traits#129]
[Despite being listed in the API docs](https://github.com/gabrielguerrero/ngrx-traits/blob/main/libs/ngrx-traits/signals/api-docs.md#witheventhandlereventhandlerfactory), [`withEventHandler`](https://github.com/gabrielguerrero/ngrx-traits/blob/main/libs/ngrx-traits/signals/src/lib/with-event-handler/with-event-handler.ts) is not exported from the library's [index.ts](https://github.com/gabrielguerrero/ngrx-traits/blob/main/libs/ngrx-traits/signals/src/lib/index.ts).

I'm just wondering if this was intentional or an oversight?

**Comment by gabrielguerrero** [comment]
Hey this is a special trait I initially set as internal is used to communicate events between traits, I have not exposed yet because I wanted to be sure I was happy with the api, and is kind of an advance use case, but I can expose it, let me think on it, will be interesting to know your use case for it , I put an @experimental jsdoc tag but that doesnt exclude it from exporting by js doc which is why is there

**Comment by Toeler** [comment]
No worries. I was going to use it to monkey-patch a fix for the other issue
I opened (as I'm still on angular 17 so can't use a fix anyway). But I
ended up coming up with an alternative workaround that at least solves my
case.

Feel free to close this. I was just confused since it showed in the API
reference.

**Comment by gabrielguerrero** [comment]
Ok I will close it, when I make the fix for version 18 I will try to back port it for version 17 as well, Ill let you know

**Comment by gabrielguerrero** [comment]
Any particular reason you have not move to 18 yet?

**Comment by Toeler** [comment]
No real reason, just technical debt and a lot of dependencies, including
internal packages that all need bumping and testing.
We have more modern apps that are on 18 so it's just a matter of juggling
priorities.
